import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Providers from "./providers";
import UserMenu from "./user-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="app-shell">
            <header className="app-nav">
              <div className="app-nav__inner">
                <Link href="/" className="app-nav__brand">
                  <span className="app-nav__label">InfoPortal</span>
                  <span className="app-nav__title">Company Hub</span>
                </Link>
                <nav className="app-nav__links">
                  <Link href="/" className="app-nav__link">
                    Home
                  </Link>
                  <Link href="/documentation" className="app-nav__link">
                    Documents
                  </Link>
                  <Link href="/projects" className="app-nav__link">
                    Projects
                  </Link>
                </nav>
              </div>
            </header>
            <UserMenu />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
